---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nginx-pod
      labels:
        app: web
        version: "1.0.0"
    spec:
      containers:
        - name: nginx-con
          image: nginx
          ports:
            - containerPort: 80

