---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  minReadySeconds: 4
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: mysql
            - name: MYSQL_USER
              value: laxman
            - name: MYSQL_PASSWORD
              value: rootroot
          volumeMounts:
            - name: mysql-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-vol
                   