---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: mysql-deploy
  targetCPUUtilizationPercentage: 50